// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     HiveTask.avsc
 *     OssTask.avsc
 *     OssTaskResult.avsc
 */

package record

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type HiveTask struct {
	JobId     string
	TraceId   string
	DatasetId string
	TaskType  string
	Remarks   string
}

func NewHiveTaskWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &HiveTask{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeHiveTask(r io.Reader) (*HiveTask, error) {
	t := NewHiveTask()

	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	return t, err
}

func NewHiveTask() *HiveTask {
	return &HiveTask{}
}

func (r *HiveTask) Schema() string {
	return "{\"fields\":[{\"name\":\"jobId\",\"type\":\"string\"},{\"name\":\"traceId\",\"type\":\"string\"},{\"name\":\"datasetId\",\"type\":\"string\"},{\"name\":\"taskType\",\"type\":\"string\"},{\"name\":\"remarks\",\"type\":\"string\"}],\"name\":\"HiveTask\",\"namespace\":\"com.pharbers.kafka.schema\",\"type\":\"record\"}"
}

func (r *HiveTask) SchemaName() string {
	return "com.pharbers.kafka.schema.HiveTask"
}

func (r *HiveTask) Serialize(w io.Writer) error {
	return writeHiveTask(r, w)
}

func (_ *HiveTask) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *HiveTask) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *HiveTask) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *HiveTask) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *HiveTask) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *HiveTask) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *HiveTask) SetString(v string)   { panic("Unsupported operation") }
func (_ *HiveTask) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *HiveTask) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.String)(&r.JobId)
	case 1:
		return (*types.String)(&r.TraceId)
	case 2:
		return (*types.String)(&r.DatasetId)
	case 3:
		return (*types.String)(&r.TaskType)
	case 4:
		return (*types.String)(&r.Remarks)

	}
	panic("Unknown field index")
}
func (r *HiveTask) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *HiveTask) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *HiveTask) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *HiveTask) Finalize()                        {}

type HiveTaskReader struct {
	r io.Reader
	p *vm.Program
}

func NewHiveTaskReader(r io.Reader) (*HiveTaskReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewHiveTask()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &HiveTaskReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *HiveTaskReader) Read() (*HiveTask, error) {
	t := NewHiveTask()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
