// Code generated by github.com/actgardner/gogen-avro. DO NOT EDIT.
/*
 * SOURCES:
 *     HiveTask.avsc
 *     HiveTracebackTask.avsc
 *     OssTask.avsc
 *     OssTaskResult.avsc
 */

package record

import (
	"github.com/actgardner/gogen-avro/compiler"
	"github.com/actgardner/gogen-avro/container"
	"github.com/actgardner/gogen-avro/vm"
	"github.com/actgardner/gogen-avro/vm/types"
	"io"
)

type ParentUrlRecord struct {
	MetaData   string
	SampleData string
}

func NewParentUrlRecordWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := &ParentUrlRecord{}
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

func DeserializeParentUrlRecord(r io.Reader) (*ParentUrlRecord, error) {
	t := NewParentUrlRecord()

	deser, err := compiler.CompileSchemaBytes([]byte(t.Schema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	err = vm.Eval(r, deser, t)
	return t, err
}

func NewParentUrlRecord() *ParentUrlRecord {
	return &ParentUrlRecord{}
}

func (r *ParentUrlRecord) Schema() string {
	return "{\"fields\":[{\"name\":\"MetaData\",\"type\":\"string\"},{\"name\":\"SampleData\",\"type\":\"string\"}],\"name\":\"ParentUrlRecord\",\"type\":\"record\"}"
}

func (r *ParentUrlRecord) SchemaName() string {
	return "com.pharbers.kafka.schema.ParentUrlRecord"
}

func (r *ParentUrlRecord) Serialize(w io.Writer) error {
	return writeParentUrlRecord(r, w)
}

func (_ *ParentUrlRecord) SetBoolean(v bool)    { panic("Unsupported operation") }
func (_ *ParentUrlRecord) SetInt(v int32)       { panic("Unsupported operation") }
func (_ *ParentUrlRecord) SetLong(v int64)      { panic("Unsupported operation") }
func (_ *ParentUrlRecord) SetFloat(v float32)   { panic("Unsupported operation") }
func (_ *ParentUrlRecord) SetDouble(v float64)  { panic("Unsupported operation") }
func (_ *ParentUrlRecord) SetBytes(v []byte)    { panic("Unsupported operation") }
func (_ *ParentUrlRecord) SetString(v string)   { panic("Unsupported operation") }
func (_ *ParentUrlRecord) SetUnionElem(v int64) { panic("Unsupported operation") }
func (r *ParentUrlRecord) Get(i int) types.Field {
	switch i {
	case 0:
		return (*types.String)(&r.MetaData)
	case 1:
		return (*types.String)(&r.SampleData)

	}
	panic("Unknown field index")
}
func (r *ParentUrlRecord) SetDefault(i int) {
	switch i {

	}
	panic("Unknown field index")
}
func (_ *ParentUrlRecord) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *ParentUrlRecord) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *ParentUrlRecord) Finalize()                        {}

type ParentUrlRecordReader struct {
	r io.Reader
	p *vm.Program
}

func NewParentUrlRecordReader(r io.Reader) (*ParentUrlRecordReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewParentUrlRecord()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &ParentUrlRecordReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r *ParentUrlRecordReader) Read() (*ParentUrlRecord, error) {
	t := NewParentUrlRecord()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
